name: Complete Run

time_config:
  start_date: 2010-1-1T00:00:00
  end_date: 2020-1-1T00:00:00

region_config:
  region: italy_csep_region
  mag_min: 5.0
  mag_max: 9.0
  mag_bin: 0.1
  depth_min: -2
  depth_max: 30

catalog: catalog.json
model_config: models.yml
test_config: tests.yml
